package entity;
// Generated Dec 12, 2018 9:05:38 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name="stock"
    ,schema="dbo"
    ,catalog="hibernateTest"
)
public class Stock  implements java.io.Serializable {


     private int stockId;
     private String stockCode;
     private String stockName;

    public Stock() {
    }

    public Stock(int stockId, String stockCode, String stockName) {
       this.stockId = stockId;
       this.stockCode = stockCode;
       this.stockName = stockName;
    }
   
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name="STOCK_ID", unique=true, nullable=false)
    public int getStockId() {
        return this.stockId;
    }
    
    public void setStockId(int stockId) {
        this.stockId = stockId;
    }

    
    @Column(name="STOCK_CODE", nullable=false, length=10)
    public String getStockCode() {
        return this.stockCode;
    }
    
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode;
    }

    
    @Column(name="STOCK_NAME", nullable=false, length=20)
    public String getStockName() {
        return this.stockName;
    }
    
    public void setStockName(String stockName) {
        this.stockName = stockName;
    }




}


